const $ = (id) => document.getElementById(id);
let state = null;
const send = (msg) => new Promise((resolve,reject)=>chrome.runtime.sendMessage(msg,r=>{if(chrome.runtime.lastError) reject(new Error(chrome.runtime.lastError.message)); else resolve(r); }));
function setStatus(text, error=false){$('status').textContent=text||'';$('status').style.color=error?'#ff9ca5':'';}
function fmt(n){return Number(n||0).toLocaleString('vi-VN');}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function applyTheme(theme){document.body.className='theme-'+theme;}
function renderRules(){const box=$('rules'); if(state.settings.stealthMode){box.innerHTML='<div class="empty">Stealth Mode đang ẩn danh sách bảo vệ.</div>';return;} if(!state.rules.length){box.innerHTML='<div class="empty">Chưa có website nào được bảo vệ.</div>';return;} box.innerHTML=state.rules.map(r=>`<div class="rule-item"><div class="rule-main"><div class="rule-tag">${esc(r.type)}</div><div class="rule-value">${esc(r.value)}</div></div><button class="btn mini" data-unprotect="${esc(r.id)}">Bỏ chặn</button></div>`).join(''); box.querySelectorAll('[data-unprotect]').forEach(b=>b.onclick=async()=>{await send({type:'unprotect-id',id:b.dataset.unprotect});await refresh();});}
function renderSmart(){const box=$('smartRules'); if(!state.smart.length){box.innerHTML='<div class="empty">Chưa có Smart Rule.</div>';return;} box.innerHTML=state.smart.map(r=>`<div class="rule-item"><div class="rule-main"><div class="rule-tag">${esc(r.matchType)}</div><div class="rule-value">${esc(r.pattern)}</div></div><button class="btn mini" data-smart="${esc(r.id)}">Xóa</button></div>`).join('');box.querySelectorAll('[data-smart]').forEach(b=>b.onclick=async()=>{await send({type:'remove-smart',id:b.dataset.smart});await refresh();});}
function renderLogs(){const box=$('logs'); if(state.settings.stealthMode){box.innerHTML='<div class="empty">Stealth Mode đang ẩn nhật ký.</div>';return;}if(!state.logs.length){box.innerHTML='<div class="empty">Chưa có hoạt động.</div>';return;}box.innerHTML=state.logs.slice(0,30).map(l=>`<div class="log"><b>${new Date(l.at).toLocaleTimeString()}</b> · ${esc(l.message)}${l.url?` · ${esc(l.url)}`:''}</div>`).join('');}
async function renderSessions(){const r=await send({type:'recent-sessions'});const box=$('sessions');const items=(r.sessions||[]).filter(s=>s.tab||s.window);if(!items.length){box.innerHTML='<div class="empty">Không có session gần đây.</div>';return;}box.innerHTML=items.map(s=>{const t=s.tab;const title=t?.title||'Cửa sổ đã đóng';const url=t?.url||'';return `<div class="rule-item session-item"><div class="rule-main"><div class="session-title">${esc(title)}</div><div class="session-url">${esc(url)}</div></div><button class="btn mini" data-restore="${esc(s.sessionId)}">Khôi phục</button></div>`}).join('');box.querySelectorAll('[data-restore]').forEach(b=>b.onclick=async()=>{const r=await send({type:'restore-session',session:{sessionId:b.dataset.restore}});if(!r.ok)setStatus(r.error||'Không thể khôi phục',true);else setStatus('Đã gửi lệnh khôi phục.');await refresh();});}
function syncUI(){if(!state)return; $('currentUrl').textContent=state.currentUrl||'Tab hiện tại không phải http/https';$('statusTitle').textContent=state.settings.autoDelete?'Protection Active':'Protection Ready';$('modePill').textContent=state.settings.autoDelete?'AUTO ON':'READY';$('browserLabel').textContent=state.browser||'Auto';$('statDeleted').textContent=fmt(state.stats.deleted);$('statBlocked').textContent=fmt(state.stats.blockedRestores);$('statRules').textContent=fmt(state.rules.length);$('statAuto').textContent=fmt(state.stats.autoDeleted);$('ruleCount').textContent=`${state.rules.length} quy tắc`;$('autoState').textContent=state.settings.autoDelete?`Đang bật · ${state.settings.intervalMinutes} phút`:'Đang tắt';$('autoDelete').setAttribute('aria-pressed',String(state.settings.autoDelete));$('interval').value=String(state.settings.intervalMinutes);$('visitDelete').checked=state.settings.historyOnVisit;$('deleteStartup').checked=state.settings.deleteOnStartup;$('oldDays').value=state.settings.deleteOldDays||'';$('dailyTime').value=state.settings.dailyCleanupTime||'';$('stealthMode').checked=state.settings.stealthMode;$('pinEnabled').checked=state.settings.pinEnabled;$('theme').value=state.settings.theme;$('browserMode').value=state.settings.browserMode||'auto';applyTheme(state.settings.theme);renderRules();renderSmart();renderLogs();}
async function refresh(){const tabs=await new Promise(r=>chrome.tabs.query({active:true,currentWindow:true},r));const r=await send({type:'dashboard'});state=r;state.currentUrl=tabs[0]?.url||'';syncUI();await renderSessions();}
async function saveSettings(patch){const r=await send({type:'set-settings',settings:patch});if(!r.ok)throw new Error(r.error||'Không thể lưu');}
for(const id of ['visitDelete','deleteStartup','oldDays','dailyTime','theme','browserMode','stealthMode'])$(id).addEventListener('change',async()=>{try{const patch={historyOnVisit:$('visitDelete').checked,deleteOnStartup:$('deleteStartup').checked,deleteOldDays:Number($('oldDays').value||0),dailyCleanupTime:$('dailyTime').value,theme:$('theme').value,browserMode:$('browserMode').value,stealthMode:$('stealthMode').checked};await saveSettings(patch);await refresh();}catch(e){setStatus(e.message,true);}});
$('interval').onchange=async()=>{try{await saveSettings({intervalMinutes:Number($('interval').value)});await refresh();}catch(e){setStatus(e.message,true);}};
$('autoDelete').onclick=async()=>{try{const enabled=$('autoDelete').getAttribute('aria-pressed')!=='true';const r=await send({type:'set-auto',enabled,intervalMinutes:Number($('interval').value)});if(!r.ok)throw new Error(r.error);await refresh();}catch(e){setStatus(e.message,true);}};
$('cleanProtect').onclick=async()=>{const r=await send({type:'clean-current',close:true});setStatus(r.ok?'Đã xóa và bảo vệ trang hiện tại.':r.error,r.ok===false);await refresh();};
$('cleanOnly').onclick=async()=>{const r=await send({type:'delete-current'});setStatus(r.ok?'Đã xóa lịch sử trang hiện tại.':r.error,r.ok===false);await refresh();};
$('wipeNow').onclick=async()=>{const r=await send({type:'wipe-now',pin:$('pinInput').value});setStatus(r.ok?'Wipe Now hoàn tất.':r.error,r.ok===false);await refresh();};
$('wipeSite').onclick=async()=>{const r=await send({type:'wipe-site',url:state.currentUrl,pin:$('pinInput').value});setStatus(r.ok?'Đã dọn dữ liệu website.':'Không thể dọn website.',!r.ok);await refresh();};
$('addRule').onclick=async()=>{try{const v=$('ruleInput').value.trim();const type=$('ruleType').value;const r=await send({type:type==='domain'?'protect-domain':'protect-url',domain:v,url:v});if(!r.ok)throw new Error(r.error);$('ruleInput').value='';await refresh();}catch(e){setStatus(e.message,true);}};
$('unprotectAll').onclick=async()=>{await send({type:'unprotect-all'});await refresh();};
$('addSmart').onclick=async()=>{const r=await send({type:'add-smart',pattern:$('smartPattern').value,matchType:$('smartType').value,actions:{deleteHistory:$('smartDelete').checked,protect:$('smartProtect').checked,siteWipe:$('smartWipe').checked}});setStatus(r.ok?'Đã thêm Smart Rule.':r.error,r.ok===false);await refresh();$('smartPattern').value='';};
$('refreshSessions').onclick=renderSessions;$('clearLogs').onclick=async()=>{await send({type:'clear-logs'});await refresh();};$('clearAll').onclick=async()=>{const r=await send({type:'wipe-now',pin:$('pinInput').value});setStatus(r.ok?'Đã xóa toàn bộ lịch sử.':r.error,r.ok===false);await refresh();};$('resetStats').onclick=async()=>{await send({type:'reset-stats'});await refresh();};
$('savePin').onclick=async()=>{const r=await send({type:'pin-set',pin:$('pinInput').value});setStatus(r.ok?'Đã bật PIN Lock.':r.error,r.ok===false);await refresh();};$('disablePin').onclick=async()=>{const r=await send({type:'pin-disable'});setStatus(r.ok?'Đã tắt PIN.':r.error,r.ok===false);await refresh();};
$('exportBackup').onclick=async()=>{const r=await send({type:'export'});const blob=new Blob([JSON.stringify(r.payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`history-guard-pro-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);};
$('importBackup').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const p=JSON.parse(await f.text());const r=await send({type:'import',payload:p,pin:$('pinInput').value});setStatus(r.ok?'Import thành công.':r.error,r.ok===false);await refresh();}catch(err){setStatus('File JSON không hợp lệ.',true);}e.target.value='';};
$('openOptions').onclick=()=>chrome.runtime.openOptionsPage();$('openSidePanel').onclick=async()=>{try{const w=await new Promise(r=>chrome.windows.getCurrent(r));if(chrome.sidePanel?.open) await chrome.sidePanel.open({windowId:w.id});}catch(e){setStatus('Không thể mở Side Panel trên trình duyệt này.',true);}};
refresh().catch(e=>setStatus(e.message,true));
